# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_image', models.ImageField(max_length=200, upload_to='')),
                ('content', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ManyToManyField(to='blog.Comment'),
        ),
    ]
