# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161208_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_image',
        ),
    ]
